In [1]:
from numba import cuda
import math
import numba
import numpy as np

@numba.cuda.jit
def add_arrays_on_gpu(a, b, c):
    i = numba.cuda.grid(1)
    if i < a.shape[0]:
        c[i] = i

# Datos de entrada
a = np.array([1, 2, 3, 4], dtype=np.int32)
b = np.array([10, 20, 30, 40], dtype=np.int32)
c = np.empty_like(a)

# Configuración de la cuadrícula de hilos
threads_per_block = 4
blocks_per_grid = (a.shape[0] + (threads_per_block - 1)) // threads_per_block

# Llamada a la función en la GPU
add_arrays_on_gpu[blocks_per_grid, threads_per_block](a, b, c)

print(c)


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[0 1 2 3]


/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))


In [2]:
import numpy as np
import numba
from numba import cuda

# Función que suma dos matrices en la GPU
@cuda.jit
def add_matrices_on_gpu(A, B, C):
    i, j = cuda.grid(2)
    if i < A.shape[0] and j < A.shape[1]:
        # C[i, j] =j
        C[i, j] = A[i, j] + B[i, j]

# Definir las dimensiones de las matrices
rows = 3
cols = 3

# Crear dos matrices aleatorias en la CPU
A=np.array([[0, 40, 50, 10, 80, 20],
            [40, 0, 90, 30, 100, 80],
            [50, 90, 0, 60, 30, 10],
            [10, 30, 60, 0, 70, 40],
            [80, 100, 30, 70, 0, 50],
            [20, 80, 10, 40, 50, 0]]).astype(np.float32)

B=np.array([[0, 40, 50, 10, 80, 20],
            [40, 0, 90, 30, 100, 80],
            [50, 90, 0, 60, 30, 10],
            [10, 30, 60, 0, 70, 40],
            [80, 100, 30, 70, 0, 50],
            [20, 80, 10, 40, 50, 0]]).astype(np.float32)

# A = np.random.rand(rows, cols).astype(np.float32)
# B = np.random.rand(rows, cols).astype(np.float32)

# Crear matrices vacías para almacenar el resultado en la CPU
C = np.empty_like(A).astype(np.float32)

# Definir las dimensiones del bloque y la cuadrícula
threads_per_block = (16, 16)
blocks_per_grid_x = (A.shape[0] + threads_per_block[0] - 1) // threads_per_block[0]
blocks_per_grid_y = (A.shape[1] + threads_per_block[1] - 1) // threads_per_block[1]
blocks_per_grid = (blocks_per_grid_x, blocks_per_grid_y)

# Transfiere los datos a la GPU
d_A = cuda.to_device(A)
d_B = cuda.to_device(B)
d_C = cuda.to_device(C)


# Llama a la función en la GPU
add_matrices_on_gpu[blocks_per_grid, threads_per_block](d_A, d_B, d_C)

print(A.shape[0])

# Transfiere el resultado de nuevo a la CPU
d_C.copy_to_host(C)

# Imprime el resultado
print("Matriz A:")
print(A)
print("Matriz B:")
print(B)
print("Resultado de la suma:")
print(C)


6
Matriz A:
[[  0.  40.  50.  10.  80.  20.]
 [ 40.   0.  90.  30. 100.  80.]
 [ 50.  90.   0.  60.  30.  10.]
 [ 10.  30.  60.   0.  70.  40.]
 [ 80. 100.  30.  70.   0.  50.]
 [ 20.  80.  10.  40.  50.   0.]]
Matriz B:
[[  0.  40.  50.  10.  80.  20.]
 [ 40.   0.  90.  30. 100.  80.]
 [ 50.  90.   0.  60.  30.  10.]
 [ 10.  30.  60.   0.  70.  40.]
 [ 80. 100.  30.  70.   0.  50.]
 [ 20.  80.  10.  40.  50.   0.]]
Resultado de la suma:
[[  0.  80. 100.  20. 160.  40.]
 [ 80.   0. 180.  60. 200. 160.]
 [100. 180.   0. 120.  60.  20.]
 [ 20.  60. 120.   0. 140.  80.]
 [160. 200.  60. 140.   0. 100.]
 [ 40. 160.  20.  80. 100.   0.]]


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


In [3]:
from numba import cuda,float32
import math
import numba
import numpy as np

In [4]:
from google.colab import drive
import pandas as pd
import numpy
drive.mount('/content/drive')
songs = pd.read_csv('/content/drive/My Drive/Colab Notebooks/yataros1.csv',header=None)

# dataset_sec_rec=songs.copy()
# dataset_sec_rec=dataset_sec_rec.transpose()

# dataset_sec_rec.drop(0, axis=1, inplace = True)
# dataset_sec_rec = dataset_sec_rec.iloc[1:]
# dataset_sec_rec = dataset_sec_rec.reset_index(drop=True)
# dataset_sec_rec = dataset_sec_rec.to_numpy()
# dataset_sec_rec=dataset_sec_rec.astype(numpy.float32)

songs=songs.transpose()
# print(songs.isnull().sum())

songs.drop(0, axis=1, inplace = True)
songs = songs.iloc[1:]
songs = songs.reset_index(drop=True)
dataset = songs.to_numpy()

# dataset=dataset[0:10,0:12]
dataset=dataset.astype(numpy.float64)
# n=numpy.size(dataset,axis=0)
# print(numpy.size(dataset,axis=0),numpy.size(dataset,axis=1))
# print(dataset)
cents_graph_global=[]
# print(n)

Mounted at /content/drive


In [5]:
dataset

array([[1.80646314e+03, 1.90046106e+03, 1.80997253e+03, ...,
        1.81985717e+03, 1.90887120e+03, 1.79578567e+03],
       [1.49390238e+02, 1.53020840e+02, 1.49627115e+02, ...,
        1.48267935e+02, 1.56901695e+02, 1.48714949e+02],
       [1.51722815e+02, 1.67069848e+02, 1.53549911e+02, ...,
        1.58083895e+02, 1.66423507e+02, 1.50564407e+02],
       ...,
       [3.87574681e-02, 1.09775774e-01, 1.63062430e-01, ...,
        1.54991645e-01, 2.22071003e-01, 2.36816106e-02],
       [5.02914177e+00, 4.24687834e+00, 7.32199789e+00, ...,
        4.92034191e+00, 2.51490243e+00, 2.54902411e+00],
       [9.49662362e-01, 9.21523196e-01, 9.09609639e-01, ...,
        9.51174754e-01, 8.85426506e-01, 9.70989426e-01]])

In [6]:
@cuda.jit
def edm(X_d,N,F,D_d):
    thisRow,otherRow = cuda.grid(2)
    if thisRow < N and otherRow < N:
      d = 0.0
      for f in range(F):
        d += (X_d[thisRow, f] - X_d[otherRow, f]) **2
      D_d[thisRow, otherRow] = math.sqrt(d)

@cuda.jit
def KCentresGPU(D_d,K_d,L_d,N,K):
    i = cuda.grid(1)
    minimum=math.inf
    pos=-1
    if i < N:
      for k in range(K):
        kk=K_d[k]
        if D_d[i,kk]<minimum:
          minimum=D_d[i,kk]
          pos=k
      L_d[i]=pos

@cuda.jit
def findMaximaGPU(D_d,L_d,M_d,N):
    i = cuda.grid(1)
    maximum=-1.0
    if i < N:
      cluster_label=L_d[i]
      for j in range(N):
        if cluster_label==L_d[j]:
          if D_d[i,j]>maximum:
            maximum=D_d[i,j]
      M_d[cluster_label,i]=maximum

@cuda.jit
def findMinimumOfMaximaGPU(t_d,M_d,N,K):
    k = cuda.grid(1)
    minimum=math.inf
    if k < K:
      for j in range(N):
        if M_d[k,j]<minimum:
          minimum=M_d[k,j]
          pos=j
      t_d[k]=pos

In [7]:

from timeit import default_timer
import time

def main(dataset,k,nrep=1):
  elapsed_time=0
  N=dataset.shape[0]
  F=dataset.shape[1]
  X_d = cuda.to_device(dataset)

  mat_dis=numpy.empty([N, N])
  mat_dis = mat_dis.astype(numpy.float32)
  mat_dis_gpu=cuda.to_device(mat_dis)

  threads_per_block = (32, 32)
  blocks_per_grid_x = (N + threads_per_block[0] - 1) // threads_per_block[0]
  blocks_per_grid_y = (N + threads_per_block[1] - 1) // threads_per_block[1]
  blocks_per_grid = (blocks_per_grid_x, blocks_per_grid_y)


  block=32
  grid=int((N + block - 1) / block)

  L=numpy.full((N),-1,dtype=numpy.int32)
  L_d=cuda.to_device(L)

  M=numpy.full((k,N),numpy.inf)
  M = M.astype(numpy.float32)
  M_d = cuda.to_device(M)

  t=numpy.full((k),-1,dtype=numpy.int32)
  t_d=cuda.to_device(t)
  dopt=numpy.inf
  cents_graph_Numba_c=[]



  inicio=default_timer()

  ##MEDIDA
  start_time = time.time()
  edm[blocks_per_grid, threads_per_block](X_d, N,F,mat_dis_gpu)
  finish_time = time.time()

  print("Tiempo de Matriz de distancias: ",finish_time-start_time)

  mat_dis_gpu.copy_to_host(mat_dis)

  for i in range(nrep):
    # K_h=numpy.random.permutation(N)
    # K_h=K_h[0:k]
    # K_h = K_h.astype(numpy.int32)
    # K_d=cuda.to_device(K_h)

    #inicialización de K
    K_h=np.array([3, 14, 35, 24, 39], dtype=np.int32)
    K_d=cuda.to_device(K_h)

    start_time = time.time()

    while True:
      # print("Vea esto es M", K_h)
      ##MEDIDA
      KCentresGPU[grid,block](mat_dis_gpu,K_d,L_d,N,k)
      findMaximaGPU[grid,block](mat_dis_gpu,L_d,M_d,N)
      findMinimumOfMaximaGPU[grid,block](t_d,M_d,N,k)



      # K_d.copy_to_host(K_h)
      t_d.copy_to_host(t)


      # print("Esto es k_h ", K_h, "hace las veces de M")
      # print("Esto es t", t, "hace las veces de J")
      if np.all(K_h==t):
        # print("CONVERGE")
        dmin,labs=numpy.min(mat_dis[t,:],axis=0),numpy.argmin(mat_dis[t,:],axis=0)
        dmin=numpy.max(dmin)
        break
      K_h=t.copy()
      K_d.copy_to_device(t_d)

    finish_time = time.time()
    elapsed_time+=(finish_time-start_time)
    #almacena los centros más optimos en jopt.
    if(dmin<=dopt):
        dopt=dmin
        labels=numpy.transpose(labs)
        jopt=t.tolist()


  #Determina los mejores centros sobre los N intentos.
  dm=numpy.zeros(k_length)
  for i in range(k_length):
      L=numpy.where(labels==i)[0]
      dm[i]=numpy.max(mat_dis[jopt[i],L])

  cents_graph_global.append(cents_graph_Numba_c)
  fin=default_timer()

  print("\nTiempo de K-centres:",elapsed_time/nrep)
  return labels,jopt,dm



k_length=5
# inicio=default_timer()
labels,jopt,dm=main(dataset,k_length,25)
# fin=default_timer()
# print(fin-inicio)
print("\n",labels,dm)

print("\nCENTROIDES :",jopt)


<ipython-input-7-c8bfa7c26666>:11: RuntimeWarning: overflow encountered in cast
  mat_dis = mat_dis.astype(numpy.float32)
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 4 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


Tiempo de Matriz de distancias:  0.31762123107910156


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 2 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 2 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 2 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))



Tiempo de K-centres: 0.02115602493286133

 [2 3 3 3 3 1 4 1 1 4 1 1 1 1 1 1 1 2 0 0 0 2 0 1 1 1 1 1 1 1 1 4 1 3 1 4 1
 1 4 1] [1.87170368e+08 9.36759720e+01 3.03671406e+05 1.35219824e+04
 8.05443726e+02]

CENTROIDES : [18, 24, 0, 2, 9]
